### ISSUE TITLE
Spacing for angle brackets in static_cast

### ISSUE THREAD

**Issue by meghanashankar** [TheWolfA2/183lint#2]
I had the line of code

`int num_batches = ceil(static_cast<double>(num_people)/PER_BATCH);`

and I received the feedback

`Line 46, Column 39: Incorrect spacing around < operator.`

**Comment by TheWolfA2** [comment]
Yikes. I'm surprised the Clang bindings flagged that templated function. Wonder if it does it for other templated types...

**Comment by meghanashankar** [comment]
Weirdly enough, when I submitted a lab from 280 that involved templating, I received basically the same message for this line (where there's an `istream` called `is`)

` while (is >> species >> name) {`

but not for any of the lines involving templating, such as this one

` for (List<Animal*>::Iterator i = l.begin(); i != l.end(); ++i) {`

**Comment by TheWolfA2** [comment]
Initial issue should be closed by 2a7bbe8c617fe6f04e27e52c9ad0bcafcb14dc6f.

I THINK the other issue you brought up was resolved in 5284d9927282321c1231d643abb88ede6eec2352.  Feel free to submit again and re-open this issue or #1 if either of the bugs are still there :)
