### ISSUE TITLE
spacing incorrect around ! operator

### ISSUE THREAD

**Issue by mdorf42** [TheWolfA2/183lint#3]
code:
 if (!cin || !isValidDate(month, day, year)) {

But
    if (! cin || ! isValidDate(month, day, year)) {     //gives
Line 320, Column 9: Incorrect spacing around ! operator.
Line 320, Column 18: Incorrect spacing around the unary ! operator.

**Comment by TheWolfA2** [comment]
Would it be preferred that space following an operator! not be flagged as in correct spacing? It's currently written to allow whitespace or an opening parentheses preceding it, and doesn't whitespace following it

**Comment by mdorf42** [comment]
let me check with the staff

**Comment by mdorf42** [comment]
I guess I don't understand what it currently allows

if (!cin || !isValidDate(month, day, year)) {

if (!(cin) || !(isValidDate(month, day, year))) {

if ((!cin) || (!isValidDate(month, day, year))) {

all give:

Line 320, Column 10: Incorrect spacing around ! operator.


I'm running out of possibilities to get it to pass.


I prefer the 1st one

which do you prefer?

**Comment by TheWolfA2** [comment]
My preferred style would be the first one (thought 2 and 3 are completely valid and fine with me).  It looks like it has to do with how the syntax tree is generated for the code `!cin` and `!cin.good()` and doesn't recognize the ! as an operator, but rather as an operator overload function call. Will take me a little time to see if I can find a good fix for this one...

**Comment by mdorf42** [comment]
thanks.

I also prefer the 1st one

**Comment by TheWolfA2** [comment]
After doing a little work and some testing, I've discovered some issues.  For overloaded operators, it appears there is no official way to determine the context of the operator being overloaded (for example, the difference between operator- for negation and operator- for subtracting to objects).

There is the possibility of trying to evaluate the function pointer for the overload to determine the context of the operator overload.  However, I think this will end up being very error prone.  For example, a subtraction operator overload could have these two possible pointer signatures: `MyInt &(*)(const MyInt &)` and `MyInt &(*)(const MyInt &, const MyInt &)`.

The operator! issue can be easily remedied by adding a `if currentOperator == 'operator!'` but it then breaks with other cases like a unary operator-.  Should I work on building some cases to catch issues like unary vs. binary operator+ and operator- in addition to fixing the operator! issue?

**Comment by TheWolfA2** [comment]
After looking at the list of overloadable operators and the possible signatures they can have (http://en.cppreference.com/w/cpp/language/operators), it actually may not be too hard to create this functionality. This could likely be compiled into some type of dictionary mapping operators to their possible function signatures, and then compared against the current function signature. I'll start working on this in the morning

**Comment by willwolfram18** [comment]
Fixed in commit 111cb17f86c4bd6a86581d1f0d54a00f4aefaa70
