### ISSUE TITLE
Improper handling of operator overloads

### ISSUE THREAD

**Issue by TheWolfA2** [TheWolfA2/183lint#6]
Does not catch spacing errors on operators that are overloaded by classes.  Example code that can create the bug:
```
string s = "Hello";
s = s+"goodbye";
// as well as
if (!cin || true)
{
}
```
Issue discovered by Professor Dorf in ticket #3

**Comment by willwolfram18** [comment]
Fixed in commit 111cb17f86c4bd6a86581d1f0d54a00f4aefaa70
