### ISSUE TITLE
Incorrect spacing around << operator.

### ISSUE THREAD

**Issue by GenericMonkey** [TheWolfA2/183lint#7]
![style guide extraction incorrect spacing](https://cloud.githubusercontent.com/assets/9792701/10312263/82e986b0-6c18-11e5-9443-7f3320b241a3.PNG)

The spacing shouldn't lead to a style error (it just splits a really long line on the extraction operator), but I'm getting the error in the title

**Comment by TheWolfA2** [comment]
As mentioned in our email, this is a result of using Tabs vs. spaces to begin lines.  I will consult with Professor Dorf to see if she wants this flagged as an issue or not

**Comment by GenericMonkey** [comment]
Sounds good. I think Visual Studio must auto-tab when going to the next
line, which is what caused this issue I think.

**Comment by TheWolfA2** [comment]
Confirmed by Professor Dorf to keep using spaces
